server:
  port: 8082
  servlet:
    session:
      timeout: 30ms
spring:
  redis:
    database: 1
    password:
    cluster:
      max-redirects: 3
      nodes:
        - 192.16.0.121:7000
        - 192.16.0.121:7001
        - 192.16.0.122:7000
        - 192.16.0.122:7001
        - 192.16.0.123:7000
        - 192.16.0.123:7001
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000